# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
        
name: RiotModule - Test Coverage on PR 

on:
  pull_request:

  # Manual action
  workflow_dispatch:
  
env:
     Riot_APIDevKey: ${{ secrets.RIOT_APIDEVKEY }}
     NODE_AUTH_TOKEN: ${{ secrets.PWA_TOKEN }}
     CacheEnabled: true

permissions:
   contents: read
   pull-requests: write
   packages: write  
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: TestEnv

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v4
   #   with:
   #       ref: ${{ github.event.pull_request.head.sha }}
   #       fetch-depth: 1000
   
   #  - name: Fetch base
   #   run: git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1000
        
   # Setup .npmrc file to publish to npm
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # Defaults to the user or organization that owns the workflow file
        registry-url: https://npm.pkg.github.com/
        scope: '@bedy90'
        
    - name: Install Typescript
      run: npm install typescript@5.3.3 -g
      
    - name: Install dependencies
      run: npm ci

  # ---------------------------------------
  # On Pull request
  # - Add comment test coverage in PR
  # ---------------------------------------
    - name: Run Test Coverage
      if: ${{ github.event_name == 'pull_request' }}
      run: npm run test:ts_json_coverage 

    # https://github.com/marketplace/actions/report-nyc-coverage
    - name: Report NYC coverage
      if: ${{ github.event_name == 'pull_request' }}
      uses: sidx1024/report-nyc-coverage-github-action@v1.2.7
      with:
        # Path to coverage file generated by "nyc report".
        coverage_file: "coverageJson/coverage-summary.json"
        comment_template_file: "template/comment-template.md"